### ISSUE TITLE
Unable to start the project

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs-community/adonis-packages#52]
Hello,

You have added a connection to a SQLite3 database but:

- `.env.example` need to be updated with the field `DB_CONNECTION`
- Add the need to seed database using `node ace db:seed` in the README

Also, I'm unable to start the dev server since there is a connection issue with SQLite.

```bash
esteban@Esteban-PC:~/dev/barbapapazes/adonis-packages$ node ace db:seed
/home/esteban/dev/barbapapazes/adonis-packages/node_modules/.pnpm/knex@3.1.0_sqlite3@5.1.6/node_modules/knex/lib/client.js:311
      throw new Error('Unable to acquire a connection');
            ^
Error: Unable to acquire a connection
    at Client_SQLite3.acquireConnection (/home/esteban/dev/barbapapazes/adonis-packages/node_modules/.pnpm/knex@3.1.0_sqlite3@5.1.6/node_modules/knex/lib/client.js:311:13)
    at Runner.ensureConnection (/home/esteban/dev/barbapapazes/adonis-packages/node_modules/.pnpm/knex@3.1.0_sqlite3@5.1.6/node_modules/knex/lib/execution/runner.js:305:46)
    at Runner.run (/home/esteban/dev/barbapapazes/adonis-packages/node_modules/.pnpm/knex@3.1.0_sqlite3@5.1.6/node_modules/knex/lib/execution/runner.js:30:30)
    at SchemaBuilder.Target.then (/home/esteban/dev/barbapapazes/adonis-packages/node_modules/.pnpm/knex@3.1.0_sqlite3@5.1.6/node_modules/knex/lib/builder-interface-augmenter.js:24:43)
```

**Comment by Julien-R44** [comment]
It should be OK now 
- DB_CONNECTION has been updated
- Added a seeder that will fetch and add initial packages statistics to the database

Note that the message `Unable to acquire a connection` will be displayed after running `node ace migration:fresh --seed` or `node ace db:seed`. This is a bug with `@adonisjs/cache` that I need to resolve asap. But it should work anyway

**Comment by Barbapapazes** [comment]
Perfect! works fine now!
